name: wheelbin

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    strategy:
      runs-on: ubuntu-latest
      matrix:
        python-version:
          ["3.6"]
      max-parallel: 1
      fail-fast: false
    container: "pylegacy/python:${{ matrix.python-version }}-debian-5"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build wheel
        run: |
          python setup.py sdist bdist_wheel
      -
        name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts-build
          path: dist

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          ["2.6", "2.7", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8",
           "3.9", "3.10"]
      max-parallel: 6
      fail-fast: false
    container: "pylegacy/python:${{ matrix.python-version }}-debian-5"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: artifacts-build
          path: dist
      -
        name: Install package
        run: |
          pip install dist/*.whl
      -
        name: Test package
        run: |
          python -c "import wheelbin"

  upload:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          ["3.6"]
      max-parallel: 1
    container: "pylegacy/python:${{ matrix.python-version }}-debian-5"
    environment: PyPI
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: artifacts-build
          path: dist
      -
        name: Install requirements
        run: |
          pip install --prefer-binary twine
      -
        name: Upload distributables
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
          TWINE_REPOSITORY_URL: "${{ secrets.PYPI_REPOSITORY_URL }}"
        run: |
          python -m twine check dist/*
          python -m twine upload --skip-existing dist/*
